zdania = Label(okno, text="Wprowadź ilość zdań")
zdania.grid(row=2,column=0)
przycisk_zdania=Button(okno, text = "Generuj zdania", command = przycisk_zdania) ### Możecie robić definicje ;)
przycisk_zdania.grid(row=2,column=2)
pole_zdania= Entry(okno)
pole_zdania.grid(row=2,column=1)
####
akapity = Label(okno, text="Wprowadź ilość akapitow")
akapity.grid(row=3, column=0)
pole_akapity= Entry(okno)
pole_akapity.grid(row=3,column=1)
przycisk_akapity=Button(okno, text = "Generuj akapity", command = przycisk_akapity) ### Możecie robić definicje ;)
przycisk_akapity.grid(row=3, column=2)
okno.mainloop()
